name: Build and push Docker Image

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ secrets.CR_USERNAME }} --password-stdin


      - name: Build Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ secrets.CR_USERNAME }}/face-app:latest
          docker build -t $IMAGE_NAME .

      - name: Push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ secrets.CR_USERNAME }}/face-app:latest
          docker push $IMAGE_NAME
